[package]
name = "windows-settings"
version = "0.4.2-2"
edition = "2024"
build = "build.rs"
description = "Менеджер тонкой настройки Windows 11"
authors = ["EnderMur"]
license = "MIT"
repository = "https://github.com/EnderMur/windows-settings"
homepage = "https://github.com/EnderMur/windows-settings"
readme = "README.md"
keywords = ["windows", "uwp", "appx", "debloat", "gui"]
categories = ["gui", "command-line-utilities"]

[dependencies]
eframe = { version = "0.34.2", default-features = false, features = ["default_fonts", "glow"] }
egui_extras = { version = "=0.34.2", features = ["image"] }
self_update = { version = "0.44.0", default-features = false, features = ["ureq", "default-tls"] }
self-replace = "1.5.0"
semver = "1.0.28"
ureq = { version = "3", default-features = false, features = ["native-tls"] }

[profile.release]
opt-level = 2
lto = "thin"

[profile.dev]
opt-level = 1

[build-dependencies]
embed-resource = "3.0.9"
